# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr=np.random.randint(1,100,size=(3,3))
print(arr)


[[79 96 57]
 [19 69 65]
 [20 64 87]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
arr=np.zeros((5,5))
n=0
for i in range(1,5):
    for j in range(0,5):
        if (i == (j+1)):
            arr[i][j]=n+1
            n=n+1
        else:
            continue
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
arr=np.zeros((8,8))
n=0
for i in range(0,8):
    for j in range(0,8):
        if ((i+j)%2 == 0):
            arr[i][j]=0
        else:
            arr[i][j]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [9]:
import numpy as np
x= np.random.randint(1,99,size=(5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[56 97 51 21 20]
 [14 20 70 27 82]
 [63 49 33 62 15]
 [17 53 64 48 12]
 [40 91 56 62 23]]
After normalization:
[[0.51764706 1.         0.45882353 0.10588235 0.09411765]
 [0.02352941 0.09411765 0.68235294 0.17647059 0.82352941]
 [0.6        0.43529412 0.24705882 0.58823529 0.03529412]
 [0.05882353 0.48235294 0.61176471 0.42352941 0.        ]
 [0.32941176 0.92941176 0.51764706 0.58823529 0.12941176]]


# 5.  How to find common values between two arrays?

In [12]:
import numpy as np
array1 = np.array(([0, 10], [20, 40], [2, 54]))
print("Array1: \n",array1)
array2 = np.array(([10, 30],[3, 40], [0, 11]))
print("Array2: \n",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1: 
 [[ 0 10]
 [20 40]
 [ 2 54]]
Array2: 
 [[10 30]
 [ 3 40]
 [ 0 11]]
Common values between two arrays:
[ 0 10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [13]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

comparison = (A == B)
if (comparison.all()):
    print("Equal")
else:
    print("Not equal")

Equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
def largest(vec,n): 
    max = vec[0] 
    for i in range(1, n): 
        if vec[i] > max: 
            max = vec[i]
            j=i
    vec2[j]=0
    print("Maximum element = ",max)

vec = [10, 32, 45, 90, 9, 5, 66, 1, 63, 15]
print("Original array is : ",vec)
vec2=vec
n = len(vec) 
largest(vec,n)
print("After replacing the maximum element, array is ",vec2)

Original array is :  [10, 32, 45, 90, 9, 5, 66, 1, 63, 15]
Maximum element =  90
After replacing the maximum element, array is  [10, 32, 45, 0, 9, 5, 66, 1, 63, 15]


# 9. How to print all the values of an array?

In [6]:
# To print all the values of an array, just write the function print(array_name)
import numpy as np
arr=np.array(([11,22],[33,44],[55,66],[77,88]))
print(arr)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]


# 10.Subtract the mean of each row of a matrix

In [7]:
import numpy as np
arr=np.array(([1,3],[3,5],[7,3]))
print("The Array is: \n",arr)
for i in range(0,3):
        a=arr[i].mean()
        print("Mean of row ",i," is : ",a)
        arr[i]=arr[i]-a
print("Array after subtracting mean of each row with each element in the row : \n",arr)


The Array is: 
 [[1 3]
 [3 5]
 [7 3]]
Mean of row  0  is :  2.0
Mean of row  1  is :  4.0
Mean of row  2  is :  5.0
Array after subtracting mean of each row with each element in the row : 
 [[-1  1]
 [-1  1]
 [ 2 -2]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [19]:
A = np.ones(10)
B = np.random.randint(0,len(A),20)
A += np.bincount(B, minlength=len(A))
print(A)

[5. 2. 3. 4. 1. 2. 2. 4. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [21]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print("Array 1 : \n",A,"\nArray 2 : \n",B)
np.sum(A * B.T, axis=1)


Array 1 : 
 [[5 0 7]
 [1 1 7]
 [4 6 3]] 
Array 2 : 
 [[1 1 7]
 [8 8 5]
 [5 7 9]]


array([40, 58, 85])

# 13.How to find the most frequent value in an array?

In [24]:
arr = np.random.randint(0,10,50)
print ("Array is : \n",arr)
print('Most frequent value is : ', np.bincount(arr).argmax())

Array is : 
 [0 3 5 0 5 9 1 6 3 3 1 1 8 4 0 0 1 7 2 9 3 1 2 7 7 7 3 0 5 1 2 5 2 0 9 6 7
 5 8 5 4 0 5 1 1 7 8 3 1 2]
Most frequent value is :  1


# 14.How to get the n largest values of an array

In [29]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [37]:
arr = np.array([("Hi", 9.5, 13),
              ("Hello", 3.6, 32)])
rec = np.core.records.fromarrays(arr.T, names='col1, col2, col3')
print("Regular array : \n",arr)
print("Record array : \n",rec)

Regular array : 
 [['Hi' '9.5' '13']
 ['Hello' '3.6' '32']]
Record array : 
 [('Hi', '9.5', '13') ('Hello', '3.6', '32')]
